channels:
  - conda-forge
  - nodefaults

dependencies:
  - python ==3.11.*
  # reproducibility
  - conda-lock
  # build
  - pip
  - nodejs >=18,<19
  - doitoml-with-all
  - flit >=3.9.0,<4.0.0
  - importnb
  - jupyterlite
  - jupyterlite-core ==0.1.2
  - jupyterlite-pyodide-kernel ==0.1.1
  # lint
  - black-jupyter
  - mypy
  - nbqa
  - ruff
  - ruff
  - taplo
  # work with epub files
  - ebooklib
  # work with .whl files
  - wheel
  # heavyweight editing
  - jupyterlab >=3.5,<4
  - ipywidgets
  - ipylab
  - ipydatagrid
  # testing
  - pytest-cov
  - pytest-html
  # docs
  - mdit-py-plugins >=0.3.1,<0.4
  - myst-nb
  - pydata-sphinx-theme
  - python-libarchive-c
  - sphinx-autodoc-typehints
  - sphinx-copybutton
  - sphinx-design
  - sphinxext-rediraffe
