#!/usr/bin/env python3
import subprocess
import os
import sys

if __name__ == "__main__":
    os.environ.update(IN_BINDER="1")
    # TODO: use the doit api
    sys.exit(subprocess.call(["doit", "binder"]))
